### ISSUE TITLE
Wierd Characters in Command

### ISSUE THREAD

**Issue by DamonOnYT** [josh-tf/fxcommands#10]
![image](https://user-images.githubusercontent.com/20586245/193998039-8da7d364-66af-4285-a47c-255f536720d2.png)

When using it to type a command, it adds some weird characters around each side?

The command is listening for a chat message, is not a registered one which is why I think its bringing this behaviour

**Comment by josh-tf** [comment]
Where is the slash coming from, is that included in the stream deck command?
Looks like whatever is logging to discord might be including the additional characters (inc the slash?)

This is the structure of the packet https://github.com/EggRP/fxcommands/blob/main/FXCommands/ConnectionManager.cs#L22-L36

After the command there is a null byte terminator, prior to the command text is the console command, version string, length and padding

Are you able to get your chat handler to print the char codes for those missing characters, might give some clues

**Comment by DamonOnYT** [comment]
> Where is the slash coming from, is that included in the stream deck command? Looks like whatever is logging to discord might be including the additional characters (inc the slash?)

> Are you able to get your chat handler to print the char codes for those missing characters, might give some clues


I've got nothing extra in the stream deck other than the command itself. I'll work on getting the char codes tomorrow when I have a bit of spare time to try work it out

![image](https://user-images.githubusercontent.com/20586245/194520381-048af3ed-fcf8-40fe-abd7-059957f90426.png)

**Comment by josh-tf** [comment]
With your `/me` command handler is it registered as a command or you are searching chat messages starting with `me` ?

The plugin doesn't send the slash along with the command so the discord output which includes the slash may also be adding the other characters or something - let me know how you go with the char codes when you get a chance

**Comment by DamonOnYT** [comment]
> With your `/me` command handler is it registered as a command or you are searching chat messages starting with `me` ?
> 
> The plugin doesn't send the slash along with the command so the discord output which includes the slash may also be adding the other characters or something - let me know how you go with the char codes when you get a chance

I'm listening for chat messages starting with `/me`. It's a bit of a weird way but I had issues having it show up in server logs without a bunch of additional work which created a vulnerability in the logging script. There's prob a way to make it work but that's for another day.

**Comment by josh-tf** [comment]
hmm that won't work because using `/me` or `me` in the console through the plugin won't get picked up by the chat handler AFAIK

Maybe you could try a workaround like `say /me test` and see if that could work?
