### ISSUE TITLE
Stream Deck Mini. No ANTIVIRUS INSTALLED

### ISSUE THREAD

**Issue by HazardousDzae** [josh-tf/fxcommands#12]
The plugin was working until suddenly the FXCommands plugin stopped showing up? I have tried to uninstall and reinstall. I have also reset my entire stream deck and got rid of all the files. but the deck still wont allow me to add the plugin. It is stating that there are commands that are already installed, but fx wont show up and the profile i use no longer works. I really need it for EggRP. is there anything i can do to make the FXcommands plugin work again? and No i do not have any antivirus or security blocks. i have triple checked.

**Comment by josh-tf** [comment]
Do you see `com.egg-rp.fxcommands.exe` in task manager?

Have you tried cleaning it from appdata when reinstalling (`C:\Users\(YOUR USERNAME)\AppData\Roaming\Elgato\StreamDeck\Plugins\com.egg-rp.fxcommands.sdPlugin`

**Comment by HazardousDzae** [comment]
IT WORKED!! (the task manager and finding the file) THANK YOU!
