### ISSUE TITLE
Enable more characters in commands for other languages.

### ISSUE THREAD

**Issue by rubenciito7** [josh-tf/fxcommands#16]
Hello! When using the streamdeck plugin for fivem and placing, for example, a command (/me) with tildes typical of other languages (á)​​such as Spanish, or the character "ñ" and even the question mark (¿) do not work when placing them. Could something be done to include them? Thanks in advance.

**Comment by rubenciito7** [comment]
I have two commands written in this case with these characters and as you can see, they don't work.

[COMMANDS]

me Le coloca el dedo índice y el dedo medio sobre el cuello bajo el ángulo del mentón y aplica presión muy ligeramente en busca de pulso carotídeo.

do ¿Tendría pulso? ¿Cómo sería este?

[IMAGE]

https://imgur.com/qC68xD9.png

**Comment by josh-tf** [comment]
Do these work if you do the command in console manually?

**Comment by rubenciito7** [comment]
> Do these work if you do the command in console manually?

Yes. If I put them manually in the game console it works fine. I attach an image.

[IMAGE]

https://imgur.com/uoImKEc.png

**Comment by rubenciito7** [comment]
The thing is, that the characters that it does not identify are replaced by "?"

As are the tildes, the word "ñ" and also the question mark backwards "¿"

**Comment by rubenciito7** [comment]
Hello again! Can you tell me if this only happens to me or is it something that happens to everyone with these characters and letters?

**Comment by josh-tf** [comment]
Hi, I haven't had a chance to test or look in to it yet but I assume it would affect everyone - it may be a limitation of the protocol, fivem or may be a simple change required in the plugin

**Comment by rubenciito7** [comment]
> Hi, I haven't had a chance to test or look in to it yet but I assume it would affect everyone - it may be a limitation of the protocol, fivem or may be a simple change required in the plugin


Okeyy. That change in the plugin should be done by me? If so, I don't know how to do it.

**Comment by josh-tf** [comment]
Hello, this is supported in the latest update:

https://github.com/EggRP/fxcommands/commit/1743f0630b6ff8f855379e138eb6583423d2907c

![image](https://github.com/EggRP/fxcommands/assets/25597681/27fa751c-fc95-427a-a3b1-66caad27eb09)

You can download the latest release from the releases page, I will have it updated in the Streamdeck plugins store shortly:

https://github.com/EggRP/fxcommands/releases/tag/v1.1.0

**Comment by rubenciito7** [comment]
> Hello, this is supported in the latest update:
> 
> [1743f06](https://github.com/EggRP/fxcommands/commit/1743f0630b6ff8f855379e138eb6583423d2907c)
> 
> ![image](https://user-images.githubusercontent.com/25597681/244246278-27fa751c-fc95-427a-a3b1-66caad27eb09.png)
> 
> You can download the latest release from the releases page, I will have it updated in the Streamdeck plugins store shortly:
> 
> https://github.com/EggRP/fxcommands/releases/tag/v1.1.0


It works perfectly. Thank you very much for updating it, fixing it and everything!! <3

**Comment by josh-tf** [comment]
Awesome, you're welcome!
I will close this - if you have any new ones come up please open a new issue
