### ISSUE TITLE
When I do a me command it starts with an e. So if I have it to "me test" it'll come out as "e test"

### ISSUE THREAD

**Issue by ghost** [josh-tf/fxcommands#17]

**Comment by josh-tf** [comment]
Do you have access to the command handler on the server side so we can see how it's processing the command?

**Comment by josh-tf** [comment]
Hello, there has been a new updated - please uninstall then download the latest release and let me know if its not working: 

https://github.com/EggRP/fxcommands/releases/tag/v1.1.0
