### ISSUE TITLE
Other commands

### ISSUE THREAD

**Issue by niterfjord** [josh-tf/fxcommands#18]
Hello

When I push the button with the command "naaminradio B-29 Pierre P" (it's to set my name in the radio), it sets this name in the radio:
![image](https://github.com/EggRP/fxcommands/assets/66115112/5731359d-24e7-4777-9fce-e691d4c4d80f)

When I push the button with the command "id" and "escort", It doesn't work.

**Comment by josh-tf** [comment]
Do you have the command handling code for review?

**Comment by niterfjord** [comment]
![image](https://github.com/EggRP/fxcommands/assets/66115112/c777f655-6943-443e-8c60-fc7bb2d6db15)
 
This? Or what do you mean?

**Comment by josh-tf** [comment]
On the server end, the code to register the command so I can see how its processing the text
If you don't run the server, you may need to contact the staff

**Comment by niterfjord** [comment]
I know they use QBCore but since it's a Dutch command, I think they added it themselves. I opened a ticket on their Discord to ask once.

**Comment by niterfjord** [comment]
> If you don't run the server, you may need to contact the staff

That will eventually become a bit difficult that they give their code publicly. Is there no other way you could solve/test this?

**Comment by josh-tf** [comment]
They don't really need to publicise their custom code, just confirm how exactly they are interpreting the command

Are they using RegisterCommand with arguments, are they using the rawCmd variable and trimming off X characters or using regex or string replace to remove the command and slash to get the rest of the command

This is needed to see what they are doing, this is how its done on our server and it works fine:

```
RegisterCommand('me', function(source, args, raw)
	local text = string.gsub(raw, "me ", "")
    TriggerServerEvent('utils:shareMeDisplay', text)
end)
```

or

```
RegisterCommand('e', function(source, args, raw)
	if CanDoEmote() then
		if not args[1] then
			return showNotification("No emote name was provided, you can view the list of emotes in the <b>F1</b> menu", "danger")
		end
	
		if args[1] == "sitchairf" then
			args[1] = "sitchair"
			SetEntityHeading(PlayerPedId(), GetEntityRotation(PlayerPedId()) - 180)
			EmoteCommandStart(source, args, raw)
		else
			EmoteCommandStart(source, args, raw)
		end
	end
end)
```

**Comment by niterfjord** [comment]
Does this help you further?

![](https://user-images.githubusercontent.com/66115112/243466719-54bd358a-5c27-408a-a257-e6ce6f99360d.png)

![](https://user-images.githubusercontent.com/66115112/243466758-05468843-e369-4723-a040-6ce2e032da73.png)

**Comment by josh-tf** [comment]
Can you see if it works with slightly modified logic

They can try change the `local customizedName..` line to:

`local customizedName = string.gsub(rawCommand, (Config.RadioListChangeNameCommand .. " "), "")`

and see if that works?

**Comment by niterfjord** [comment]
Thanks! But I can ask but I would also find it weird should someone ask me to modify the code on my server. For example, is there no solution that you change something in the code of the plugin so that it can work?

**Comment by josh-tf** [comment]
Hello, this has now been fixed in the latest update:

https://github.com/EggRP/fxcommands/commit/39098c3efbbfcec4f3bdd8b67747555a7840dec3

You can download the latest release from the releases page, I will have it updated in the Streamdeck plugins store shortly:

https://github.com/EggRP/fxcommands/releases/tag/v1.1.0

**Comment by niterfjord** [comment]
Thanks, the only thing I see now is the bullet before my name:
![](https://user-images.githubusercontent.com/66115112/244385991-14e0fa7e-08fd-4f7a-b46d-37a93cc54430.png)

**Comment by niterfjord** [comment]
Thanks, the only thing I see now is the bullet before my name:
![](https://user-images.githubusercontent.com/66115112/244385991-14e0fa7e-08fd-4f7a-b46d-37a93cc54430.png)

Can this also be solved?
