### ISSUE TITLE
Compile guide

### ISSUE THREAD

**Issue by benzon** [josh-tf/fxcommands#2]
Hey,

Just trying to play abit around with this to see if i can find the logic in making some changes i wanna do, but how to i build this, i get an error currently when trying to build.

```
 Error: The plugin path doesn't exist:
 ```

**Comment by josh-tf** [comment]
Hi @benzon 

You need to open the solution in Visual Studio and build the project first, it will be output to the `.\FXCommands\bin\Debug\com.egg-rp.fxcommands.sdPlugin` folder and then you can run the `CreatePackageInstaller.bat` to compile the plugin which will output to the `.\Releases` folder

**Comment by benzon** [comment]
What libs should be installed to compile this project if i may ask ?

**Comment by josh-tf** [comment]
You should be able to open the VS Solution file and then build right away, are you getting an error when trying to do this?

![image](https://user-images.githubusercontent.com/25597681/181874623-ea7b3e8d-81f8-4b2b-86ab-0955a40e65a9.png)

Have a look in the `packages.config` file, these are all included in the `packages` folder in the source code.
