### ISSUE TITLE
the whole plugin doesnt work

### ISSUE THREAD

**Issue by Pinda123** [josh-tf/fxcommands#20]
i cant add more from the bar on the right, i need to install it every time and it doesnt work. all the tiles are full with run command with a ?. i use this with everything so please fix this

**Comment by Pinda123** [comment]
![image](https://github.com/EggRP/fxcommands/assets/136327664/aab277b8-48ec-4555-ba38-e884e937aa29)

**Comment by josh-tf** [comment]
You may need to whitelist it in your Antivirus, you can see if that helps - a few other users have had similar issues resolved this way

**Comment by Pinda123** [comment]
hi josh,

i dont have a antivirus atm so i dont think thats the issue.
it worked fine for me like 2 weeks ago but it doesnt work anymore

**Comment by Drewman91** [comment]
Have you tried cleaning it from appdata when reinstalling (C:\Users\(YOUR USERNAME)\AppData\Roaming\Elgato\StreamDeck\Plugins\com.egg-rp.fxcommands.sdPlugin
