### ISSUE TITLE
Problems with installing the plugin

### ISSUE THREAD

**Issue by ghost** [josh-tf/fxcommands#21]
My friend wanted to install the fxcommands plugin but we have one problem. He can't install the plugin we have tried restating the PC installing it several times again and we also tried deleting stream deck software and installing it agian. so does anyone have a sollution for this

**Comment by Drewman91** [comment]
Have you tried cleaning it from appdata when reinstalling (C:\Users\(YOUR USERNAME)\AppData\Roaming\Elgato\StreamDeck\Plugins\com.egg-rp.fxcommands.sdPlugin
