### ISSUE TITLE
Plugin not Working 

### ISSUE THREAD

**Issue by Loke17100** [josh-tf/fxcommands#23]
Hello! Firstly Ive been using this plugin for months with no issues. Recently when I logged into the Fivem server, **I found I wasn't able to use any of the commands.** When I would click t**he commands the button would flash a caution signal.** I've tried to restart my PC and the app but nothing has worked.

**Comment by josh-tf** [comment]
Hey there,
It sounds like the plugin may be missing or has been uninstalled, or may be failing for some reason.

Could you try checking the logs:

`%appdata%\Elgato\StreamDeck\logs on Windows`

You can also try a clean install of the plugin
