### ISSUE TITLE
FiveM Radial Menu Keybind

### ISSUE THREAD

**Issue by dking2223** [josh-tf/fxcommands#24]
I'm wondering how to use a command prompt to build an action link. For example, to escort, or put in or take out of a car. 

In my city, I have to flex and hold F1 to bring up the radial, then I can click the mouse on the next option, so on and so on. Or I can flex F1 and then hit 1 then 5 then 6 for the final command for it to work for me but I'm not sure how to build that in the deck so the F1 will stay long press through the duration of the 1,5,6 combo that needs to follow it and then execute the command.

**Comment by josh-tf** [comment]
I'm not sure of a way to hold down a key (I believe that's what you are after), unfortunately you might not be able to do this using the FxCommands plugin alone

Honestly the easiest solution for you would be if the server owner could add command support to the radial wheel for use cases like this, then that way you could being something like `/wheelslot 1` or `/wheelslot 2` etc - As a server owner we would accommodate a request like this as it only takes a minute to implement, maybe worth asking them?
