### ISSUE TITLE
Command Not Executed

### ISSUE THREAD

**Issue by nick-perry14** [josh-tf/fxcommands#3]
After installing, the command does not work.  It just creates and empty line in my f8 console regardless of what I type into the commandPressed or commandReleased

**Comment by josh-tf** [comment]
There shouldn’t be any output in the console unless the command itself has an output

you’re not including a slash are you? (Slash not required)

**Comment by nick-perry14** [comment]
Negative.  But the command isn't executing either from what I can see

**Comment by josh-tf** [comment]
and the command works fine when manually entering in to the chat box or F8 console?
What if you try a command like `cmdlist` this should be available on any server and should show an output in the F8 console

Other things to check, try temporarily disabling your anti-virus software as it may be blocking the outgoing connection from the plugin (even though its local only)
