### ISSUE TITLE
Suggestion: StreamerBot

### ISSUE THREAD

**Issue by Steev93** [josh-tf/fxcommands#30]
Hello,

Is there a way to have this running via StreamerBot, 
So if a user receives so many subs or bits it does things in FiveM, like force eject, explode, seatbelt...

**Comment by chrispiciullo** [comment]
Streamer.bot can't send commands out to the Stream Deck to trigger actions. It can only receive button presses from the Stream Deck to trigger actions within Streamer.bot.
