### ISSUE TITLE
Installation won't work 

### ISSUE THREAD

**Issue by Taddybar** [josh-tf/fxcommands#4]
Hey 

Attempted to download the FxCommand plugin but after installing the plug in would not pop up on the right hand side despite it saying uninstall. After closing the store and going to the FxCommand again it says to reinstall it. I am not too sure if this may be a stream deck issue, below is what it looks like after attempting to install

Thanks 
![image](https://user-images.githubusercontent.com/110342275/182030924-dd6e6730-e728-4f01-9897-b28381c24a84.png)

**Comment by josh-tf** [comment]
Hey mate, have a look here for some ideas:

https://www.reddit.com/r/elgato/comments/q491z0/elgato_stream_deck_installed_plugins_not_showing/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

some users have found their Antivirus causing issues with Stream Deck and plugins, another user of this plug-in was having issues and was able to get it working after adding an exception to his AVG software

**Comment by Taddybar** [comment]
Hey Josh

Still got nothing unfortunately, attempted to do exceptions with it as well as the ideas on reddit. Not to sure whats causing the issue with it nor the reason why, not a major issue but thanks for the help mate

**Comment by josh-tf** [comment]
Closing as resolved via other channel (full reinstall sorted)
