### ISSUE TITLE
Not loading into Streamdeck

### ISSUE THREAD

**Issue by lukecornwill** [josh-tf/fxcommands#5]
So i have downloaded the plug in from both elgato and here 
It says its installed but isnt physically showing on my deck profile - any ideas? I ahve uninstalled streamdeck and its still not working, worked once and has now disappeared 

![image](https://user-images.githubusercontent.com/110467933/182368460-7a0b59e1-b39a-4d00-ad32-1cfe9e4cc71d.png)
![image](https://user-images.githubusercontent.com/110467933/182368536-41e10e8a-e502-4589-89fb-9cf73350065c.png)

**Comment by josh-tf** [comment]
Can you please see if you have any luck with this https://github.com/EggRP/fxcommands/issues/4#issuecomment-1200457249

**Comment by lukecornwill** [comment]
Are you saying a uninstall and re install?

**Comment by josh-tf** [comment]
You can try that, also try temporarily disabling your antivirus and seeing it that helps

**Comment by lukecornwill** [comment]
So I uninstalled and re installed the streamdeck software then re installed the fox commands and it’s still not showing up?

**Comment by josh-tf** [comment]
Please try disabling your antivirus and then running it, see if that helps?
Maybe it is blocking the plugin due to local network connection

**Comment by lukecornwill** [comment]
Have disable the av and its still the same.

Could it be because stream deck was updated?

**Comment by josh-tf** [comment]
I don't think its to do with any Stream Deck update, there are 100s of people currently using the plugin

Are you having the same issue with other plugins? I might suggest the Stream Deck forums as they may have some other troubleshooting steps for plugin install issues
