### ISSUE TITLE
Wheel Actions???

### ISSUE THREAD

**Issue by worgatah** [josh-tf/fxcommands#6]
Is there a way to make an action bypass an action wheel. For example if i'm a cop and i want to escort someone but the t /escort does not work except for in the F1 action wheel. select work. select officer action. select escort. or put in car, pull out of car....etc. I have seem to run into a dead end with this. any help would be extremely appreciated.

**Comment by josh-tf** [comment]
Unfortunately this would require the server owner to add a command to do that action, we've added a few new useful commands to our server for Stream Deck users to make life easier
