### ISSUE TITLE
Direct commands and "me" commands not executing

### ISSUE THREAD

**Issue by SkilledAlpaca** [josh-tf/fxcommands#8]
**FxCommands Version:** 1.0
**StreamDeck Software Version:** 5.2.1.15025
**FiveM Version:** 2612
**Broken Commands:** `me` and `cash`
**Expected Behavior:** Display a `/me blinks` or `/cash` which displays cash on character
**Actual Behavior:** Empty line in F8 log, no output
**Manual Command in F8 Works:** Yes, performing `me blinks` or `cash` in the F8 log work
**F8 Log:** ![image](https://user-images.githubusercontent.com/26860324/185208442-9e740685-6a56-4e5e-a452-d50b285ac161.png)
**Other:** `/e` commands without issue and I am unable to perform a `cmdlist` in my server. This server uses SaltyChat v3.1.0

**Comment by josh-tf** [comment]
Looks like SaltyChat might be handling commands differently, instead of being a registered command its checking for a chat input beginning with / or something, so these wouldn't be available via console if that's the case

What if you try something like `say /cash` as the command, does that do anything?
Not too familiar with how SaltyChat works

**Comment by josh-tf** [comment]
Sorrry, I've just re-read your issue

In the Stream Deck command, you're not including the slash are you?

You mentioned `e` works for emotes, so doesn't look like the commands are being blocked or not reaching the console if some of them work

and to confirm, `me hello` works fine in console, but when you add `me hello` to the Stream Deck command it does nothing?

No output is expected from commands, and for `cmdlist` you might need to launch in beta mode or developer mode (in FiveM main menu settings) as its a developer command, but that's more just to test that commands are reaching the console from the Stream Deck

**Comment by SkilledAlpaca** [comment]
> In the Stream Deck command, you're not including the slash are you?

Correct. I am using `e passout` without the `/`

> You mentioned e works for emotes, so doesn't look like the commands are being blocked or not reaching the console if some of them work

Correct, this works without issue. 
![image](https://user-images.githubusercontent.com/26860324/185308305-9e204c65-2bcd-48f7-b83a-a981dc7df490.png)

> and to confirm, me hello works fine in console, but when you add me hello to the Stream Deck command it does nothing?

Correct. Inputting `me hello` or `me unconscious` directly into the F8 console works. The below command does not work. 
![image](https://user-images.githubusercontent.com/26860324/185308092-7db873f4-d551-4351-aed9-12913336fbe5.png)

This is the cash command, same as above. Typing `cash` directly into the F8 console works as does the command `/cash` in the regular `T` menu. 
![image](https://user-images.githubusercontent.com/26860324/185308029-b05bb6fc-22ae-4d66-a94b-35684e05a527.png)

> No output is expected from commands, and for cmdlist you might need to launch in beta mode or developer mode (in FiveM main menu settings) as its a developer command, but that's more just to test that commands are reaching the console from the Stream Deck

Unfortunately I don't have access to this and I am doubtful the development team would provide it.

**Comment by josh-tf** [comment]
Hmm, this is strange - it is working for me with a simple test
Are you able to setup a local server with a simple command to see if its working for you? That would let us work out if its something to do with the server or your client

![image](https://user-images.githubusercontent.com/25597681/185364056-4fa0ff6e-9a3b-4c57-b73d-9c69b99f4e9f.png)

If you know how to use wireshark that would help too so we can make sure the packet looks right, but if the emote command works without issue I don't think the problem is with that

**Comment by SkilledAlpaca** [comment]
I had attempted to setup a private FiveM instance and was unable to get it working. I did how ever, attempt to login to another server in the FiveM list and the non-working commands were working on it.

**Comment by josh-tf** [comment]
What code did you use to test it on a local server, did you setup a test command in a client.lua file which prints to console?

**Comment by SkilledAlpaca** [comment]
I joined a random public server, once I was logged in, I press the same commands on my deck. Cash wasn't a command but `me` worked through the Deck.

**Comment by josh-tf** [comment]
The issue seems to be with how the server is handling/registering commands
