### ISSUE TITLE
Is there a way or a plan to integrate this with 2 way communication for commands?

### ISSUE THREAD

**Issue by chris-cozzitech** [josh-tf/fxcommands#9]
For example, if I activate my lights via controller by accident - is there a way for the streamdeck to know that my lights are active so that A) the icon changes to show lights are active   and B) I can send the command to turn them off?  Same for if I have my gun out, etc.  I am asking because I believe there is a way to do this type of stuff in MSFS but I did not know if any connected API/interface is available for FiveM.  Thanks!

**Comment by josh-tf** [comment]
Hey mate, it is possible in theory but not something that is easily implemented

A second process to read and process the console would be required, as well as the server updating their commands to output a response (eg `LIGHTS ON` `LIGHTS OFF`) which would then be read by the plugin and it could update a status

This would need to be developed separately for each command and use case so unfortunately is out of scope of the plugin
